CREATE TABLE Channels (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    StreamUrl NVARCHAR(500) NULL,
    SourceType NVARCHAR(50) NOT NULL DEFAULT 'Live',
    IsNostalgiaMode BIT NOT NULL DEFAULT 1
);

CREATE TABLE Programs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ChannelId INT NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    MediaId INT NOT NULL,
    CONSTRAINT FK_Programs_Channels FOREIGN KEY (ChannelId) REFERENCES Channels(Id)
);

CREATE TABLE SmsQueue (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Phone NVARCHAR(20) NOT NULL,
    Message NVARCHAR(250) NOT NULL,
    IsApproved BIT NOT NULL DEFAULT 0,
    IsVip BIT NOT NULL DEFAULT 0,
    ReceivedAt DATETIME NOT NULL DEFAULT GETUTCDATE()
);
