CREATE TABLE Channels (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Description NVARCHAR(500) NULL,
    StreamUrl NVARCHAR(1000) NULL,
    SourceType NVARCHAR(40) NOT NULL DEFAULT 'Live'
);

CREATE TABLE Programs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ChannelId INT NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    MediaId INT NULL,
    CONSTRAINT FK_Programs_Channels FOREIGN KEY (ChannelId) REFERENCES Channels(Id)
);

CREATE TABLE SmsMessages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Sender NVARCHAR(100) NOT NULL,
    Body NVARCHAR(500) NOT NULL,
    IsApproved BIT NOT NULL DEFAULT 0,
    IsVip BIT NOT NULL DEFAULT 0,
    CreatedUtc DATETIME NOT NULL DEFAULT GETUTCDATE()
);
